version: "2"
services:
    app1:
        build: ./app
        ports:
            - "8080:8080"
    db:
        build: .
        ports:
            - "3306:3306"
        volumes:
            - /storage/docker/mysql-datadir:/var/lib/mysql
